### ISSUE TITLE
Create Mockups

### ISSUE THREAD

**Issue by HasanGokce** [HBilge/Dolphin#22]
Deadline          : `Nov 15 2020, Sunday`
Will be studied: `team`
Date : `Nov 14, 2020 Saturday`
Time: `13:00`

**Comment by hasangokce** [comment]
![Web 1920 – 10](https://user-images.githubusercontent.com/25805267/100637091-84df8a80-3343-11eb-9c1e-3876fec821ae.png)
![Web 1920 – 9](https://user-images.githubusercontent.com/25805267/100637096-8610b780-3343-11eb-87b0-39d1c4ff4d96.png)
