### ISSUE TITLE
Pycache files conflicts!

### ISSUE THREAD

**Issue by HBilge** [HBilge/Dolphin#52]
Because of cache files, Github pull gives error.

**Comment by hasangokce** [comment]
Quickest solution:
* delete folders and clone repository again

For a permanent solution we use a .gitignore file to ignore:
 * __pycache__ folders
 * .pyc file type
 * .pyo file type

Source
- https://stackoverflow.com/questions/3719243/best-practices-for-adding-gitignore-file-for-python-projects
- https://github.com/github/gitignore/blob/master/Python.gitignore

**Comment by HBilge** [comment]
I have used also pyclean to clean pyc files. 
https://pypi.org/project/pyclean/

**Comment by HBilge** [comment]
Adding pyc to .gitignore also worked. There is no problem now.
