### ISSUE TITLE
Declaration of authentic work

### ISSUE THREAD

**Issue by hasangokce** [HBilge/Dolphin#86]
I declare that all material presented to SWE574 is my own work. I understand that
if at any time it is shown that I have significantly misrepresented material presented to
Bogazici University any degree or credits awarded to me on the basis of that
material may be revoked.

Name: Hasan Gökçe  
Date: February 1, 2021

**Comment by hasangokce** [comment]
Name: Hasan Gökçe  Date: February 1, 2021

**Comment by kaksoy** [comment]
I declare that all material presented to SWE574 is my own work. I understand that
if at any time it is shown that I have significantly misrepresented material presented to
Bogazici University any degree or credits awarded to me on the basis of that
material may be revoked.

Name: Kerem Mert Aksoy
Date: February 1, 2021
